### ISSUE TITLE
关系混合精简导致123盘的问题

### ISSUE THREAD

**Issue by 183868hlj** [lingeringsound/adblock_auto#1]
![Screenshot_2024-03-05-01-56-31-68_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/lingeringsound/adblock_auto/assets/149270855/855bf200-03c3-4a16-9ad2-cf94ffbd2048)
混合精简（https://raw.gitmirror.com/lingeringsound/adblock_auto/main/Rules/adblock_auto_lite.txt）导致123网盘底部抬高，望修复：
https://www.123pan.com/s/mlkeVv-mBTE.html

**Comment by 183868hlj** [comment]
有群或私下联系方式吗？我不会玩这个网页，很多时候都想很方便的反馈

**Comment by lingeringsound** [comment]
!好的，感谢反馈😘
!添加放行规则
```
@@||bdad.123pan.cn^
```
!规则已经更新，自己手动更新一下就行。

**Comment by 183868hlj** [comment]
> !好的，感谢反馈😘 !添加放行规则
> 
> ```
> @@||bdad.123pan.cn^
> ```
> 
> !规则已经更新，自己手动更新一下就行。

非常感谢！
