### ISSUE TITLE
百度规则误杀

### ISSUE THREAD

**Issue by Aloazny** [lingeringsound/adblock_auto#13]
### 使用的拦截器

Via, Xbrowser(X浏览器), 嗅觉浏览器, B仔浏览器, Rians浏览器, AdGuard, uBlock

### 你使用的是那个规则?

混合规则精简版

### 问题描述

在百度搜索 "小米" 等手机品牌时，会出现黑屏，求大佬解决。

**Comment by lingeringsound** [comment]
!好的，感谢反馈！添加自定义规则
```
baidu.com#@#[class$="-ad"]
```

**Comment by Aloazny** [comment]
好的，谢谢大佬！
