### ISSUE TITLE
混合精简规则误杀了b站所有的专栏图片

### ISSUE THREAD

**Issue by 183868hlj** [lingeringsound/adblock_auto#15]
### 使用的拦截器

Via

### 你使用的是那个规则?

混合规则精简版

### 问题描述

https://raw.gitmirror.com/lingeringsound/adblock_auto/main/Rules/adblock_auto_lite.txt
混合规则精简版误杀了哔哩哔哩：
https://www.bilibili.com/  所有的专栏图片：
![Screenshot_2024-06-06-04-51-22-19_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/lingeringsound/adblock_auto/assets/149270855/d459844e-5374-431b-a346-5be4fa0ca001)

**Comment by lingeringsound** [comment]
![Screenshot_2024-06-06-08-59-26-565_mark via gp](https://github.com/lingeringsound/adblock_auto/assets/114198798/882efaa2-8b28-435e-98ab-a6b2a5cc9304)

说实话，试了很多次，没有复现出来。

**Comment by 183868hlj** [comment]
> 说实话，试了很多次，没有复现出来，你能直接把网址发过来吗？

呃，不好意思，现在又没问题了，昨晚是这两个网页没图：
https://www.bilibili.com/read/mobile?id=17485966 
https://www.bilibili.com/read/mobile?id=24209895

**Comment by lingeringsound** [comment]
好的，建议检查一下，是不是**代理工具**的问题。
和图片规则有关的是`hdslb.com`，你的图片加载不出来，像是被屏蔽了这个网站的相关域名，或者当时哔哩哔哩处在高峰期或者在维护，可能会加载不出来。

**Comment by 183868hlj** [comment]
> 好的，建议检查一下，是不是**代理工具**的问题。
> 和图片规则有关的是`hdslb.com`，你的图片加载不出来，像是被屏蔽了这个网站的相关域名，或者当时哔哩哔哩处在高峰期或者在维护，可能会加载不出来。

好的谢谢，之前不知道这些也会有影响，麻烦了。
确实，才找到这条规则，不知道是不是这条规则的问题：
baidu.com##[rl-link-data-log*="bilibili.com"]

**Comment by lingeringsound** [comment]
和这个无关，这个只会作用到`baidu.com`开头的网站，而且是**元素隐藏**的规则。

你这个问题更像是没法访问`hdslb.com`有关域名。

**Comment by 183868hlj** [comment]
> 和这个无关，这个只会作用到`baidu.com`开头的网站，而且是**元素隐藏**的规则。
> 
> 你这个问题更像是没法访问`hdslb.com`有关域名。

确实，我直接打开hdslb.com没网，没挂梯也是……
