### ISSUE TITLE
误杀油猴脚本网页

### ISSUE THREAD

**Issue by damengzhu** [lingeringsound/adblock_auto#18]
### 使用的拦截器

Xbrowser(X浏览器)

### 你使用的是那个规则?

混合规则精简版

### 问题描述

https://greasyfork.org/zh-CN/scripts/503586-%E6%9B%B4%E5%A5%BD%E7%9A%84b%E7%AB%99%E5%88%86%E4%BA%AB%E6%8C%89%E9%92%AE

**Comment by damengzhu** [comment]
![Uploading Screenshot_2024-08-14-09-04-59-515_com.mmbox.xbrowser.jpg…]()

**Comment by damengzhu** [comment]
![Uploading Screenshot_2024-08-14-09-04-59-515_com.mmbox.xbrowser.jpg…]()

**Comment by damengzhu** [comment]
![Screenshot_2024-08-14-09-04-59-515_com mmbox xbrowser](https://github.com/user-attachments/assets/9287ae26-681d-4c28-8ab9-5417cba8933b)

**Comment by lingeringsound** [comment]
收到，感谢反馈！16:00左右Github Action会自动合并。
