### ISSUE TITLE
广告未被拦截

### ISSUE THREAD

**Issue by ZM2177** [lingeringsound/adblock_auto#19]
### 网址

https://m.mimibiquge.com/2_2412/9856140_2.html

### 补充说明

求助大佬！！！该网址广告未能被拦截。也不是总拦截不下来，有时可以有时不行，刷新几道可能就没了，也可能还是有。而且如果使用该网页“护眼”按钮，在应用了该规则后会失效。
首次求助有点不熟，多多包涵。
![Screenshot_20240826_015759_mark via_edit_660407111917456](https://github.com/user-attachments/assets/f4950f3a-447b-4d8c-884a-a5841629e5c6)

### 你使用的是那个规则?

混合规则精简版

### 使用的拦截器

Via

**Comment by ZM2177** [comment]
抱歉，使用不熟

**Comment by lingeringsound** [comment]
!好的，如果使用默认UA，这个广告我已经解决了。
```
.top/*_*_vw*sbjs?$third-party
||wewrute.top^
```

!如果使用的是百度app/QQ浏览器的UA，建议换成默认，或者添加规则。

```
mimibiquge.com##[style="margin:0;padding:0;outline:0"]
##video[poster^="https://code.yykalopyy.com/"]
||code.yykalopyy.com^$third-party
```

**Comment by ZM2177** [comment]
感谢大佬🙏
