### ISSUE TITLE
该页全是广告，请更新混合精简版

### ISSUE THREAD

**Issue by 183868hlj** [lingeringsound/adblock_auto#2]
https://m.chazidian.com/r_zi_zd4E00/

![Screenshot_2024-03-23-23-33-36-98_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/lingeringsound/adblock_auto/assets/149270855/6623a509-8713-46c1-9452-ccf84ec1bed8)

**Comment by lingeringsound** [comment]
我这边看不到你说的广告😂，只有下面的**为您推荐**。

**Comment by lingeringsound** [comment]
!如果是想去掉这个，可以添加这个自定义规则。
```
m.chazidian.com##.newslist
```

**Comment by 183868hlj** [comment]
> !如果是想去掉这个，可以添加这个自定义规则。
> ```
> m.chazidian.com##.newslist
> ```

为什么所有人都看不到，就我有😭

**Comment by lingeringsound** [comment]
不知道，可能是Dns劫持😂，这广告是百度的百青藤，你可以尝试添加一些拦截的DNS规则拦截他，只需要拦截域名之类的规则就行。

**Comment by 183868hlj** [comment]
> 不知道，可能是Dns劫持😂，这广告是百度的百青藤，你可以尝试添加一些拦截的DNS规则拦截他，只需要拦截域名之类的规则就行。

谢谢哈，我试下
