### ISSUE TITLE
xchina.co图片界面视频误杀

### ISSUE THREAD

**Issue by Aloazny** [lingeringsound/adblock_auto#20]
### 使用的拦截器

AdGuard, uBlock

### 你使用的是那个规则?

混合规则

### 问题描述

打开网址 [小黄书](https://xchina.co/photo/id-6506155911613.html) 上方两个视频没法显示和播放。

**Comment by lingeringsound** [comment]
!好的，感谢反馈，添加放行规则。
```
xchina.co,xchina.fun,xchina.tv#@#[class*="ad"]
```
晚点我会合并，正好到了更新时间。

**Comment by Aloazny** [comment]
好的，谢谢大佬。
