### ISSUE TITLE
拦截不全

### ISSUE THREAD

**Issue by ZM2177** [lingeringsound/adblock_auto#24]
### 网址

https://m.mimibiquge.com/2_2412/9856161_2.html

### 补充说明

在添加如下两条规则后，依然出现拦截不全
.top/*_*_vw*sbjs?$third-party
||wewrute.top^

添加如上规则后，刚开始有效。目前不论是更新订阅规则，还是一起选择自带规则，除非刷新很多次网页有可能拦截成功，不然依然有拦截不全的问题（甚至图二中框出的网页底端空白处，存在隐藏的广告）。
![Screenshot_20240905_001032_mark via](https://github.com/user-attachments/assets/3758893c-d2c9-4176-bc2a-81fff44f0649)
![Screenshot_20240905_000711_mark via_edit_1085233050873985](https://github.com/user-attachments/assets/7738e8ca-6345-4196-946d-2731bc3b310f)

### 你使用的是那个规则?

混合规则精简版

### 使用的拦截器

Via

**Comment by lingeringsound** [comment]
![Screenshot_2024-09-05-00-24-51-185_mark.via.gp.jpg](https://github.com/user-attachments/assets/fd717871-a529-4c07-9045-ff83ff2ed7d6)

好的感谢反馈，确定用的是默认ua，规则也是最新的吗？

我这边显示是没有问题的。

**Comment by ZM2177** [comment]
是的，规则最新，默认ua发自我的手机-------- 原始邮件 --------发件人： lingeringsound ***@***.***>日期： 2024年9月5日周四 00:26收件人： lingeringsound/adblock_auto ***@***.***>抄送： ZM2177 ***@***.***>, Author ***@***.***>主    题： Re: [lingeringsound/adblock_auto] 拦截不全 (Issue #24)
Screenshot_2024-09-05-00-24-51-185_mark.via.gp.jpg (view on web)
好的感谢反馈，确定用的是默认ua，规则也是最新的吗？
我这边显示是没有问题的。

**Comment by lingeringsound** [comment]
换了百度UA出来了，但是这网站有必要用百度UA吗？我建议是百度UA只用在百度上，不要全局应用，这UA在盗版网站上除了加广告，没啥作用。

**Comment by ZM2177** [comment]
![Screenshot_20240905_003933_mark via_edit_1087027467257565](https://github.com/user-attachments/assets/cc8ded7a-19fc-442d-bd00-196c05be4944)
![Screenshot_20240905_003952_mark via_edit_1087036972138293](https://github.com/user-attachments/assets/a4f65d16-de10-4ab6-98b0-4cb3eba68d42)

**Comment by lingeringsound** [comment]
看看via的网络日志，我这边没加载出来广告，我先看看你都拦截了什么。

**Comment by ZM2177** [comment]
![Screenshot_20240905_005227_mark via](https://github.com/user-attachments/assets/fe74b1b4-edd4-4395-b4ef-075300ba1a7c)
![Screenshot_20240905_005232_mark via](https://github.com/user-attachments/assets/854619b2-19d8-459b-977a-2b85db7996cf)

**Comment by lingeringsound** [comment]
换个网站，或者开阅读模式吧。我这边加载不出来，只更新了一个百度UA下的广告拦截，你可以添加到via订阅里试试。
```
https://raw.gitmirror.com/lingeringsound/adblock_auto/main/base/%E5%85%B6%E4%BB%96.prop
```

**Comment by ZM2177** [comment]
好的，感谢大佬，辛苦啦。

**Comment by ZM2177** [comment]
大佬，我发现了问题所在了，似乎是因为via浏览器没有更新到最新版才会那样。我刚更新了via就没有再看到广告了，无论刷多少次。
