### ISSUE TITLE
YouTube黑屏

### ISSUE THREAD

**Issue by gitosyes** [lingeringsound/adblock_auto#27]
### 使用的拦截器

Via

### 你使用的是那个规则?

混合规则精简版

### 问题描述

视频只有声音没有画面

**Comment by lingeringsound** [comment]
!好的，谢谢反馈，添加自定义规则即可。
```
#@#[id^="player"] > div[class][data-version]
```

**Comment by Hiearly** [comment]
@lingeringsound 你好，可以帮忙删一下这个议题吗，它一直在我置顶，谢谢了
