### ISSUE TITLE
outlook收件箱顶部空白区域

### ISSUE THREAD

**Issue by withered233** [lingeringsound/adblock_auto#28]
### 网址

https://outlook.live.com

### 补充说明

edge移动端ublock
收件箱顶部存在去除广告消息后留下的空白区域。
![S40913-12393841_com microsoft emmx(1)](https://github.com/user-attachments/assets/4ca636b3-6ef8-414e-b1f5-93a90cee5aae)

### 你使用的是那个规则?

混合规则精简版

### 使用的拦截器

uBlock

**Comment by lingeringsound** [comment]
好的，感谢反馈！但是很抱歉，这个我解决不了，至少单靠Adblock应该是没法解决的。

**Comment by withered233** [comment]
> 好的，感谢反馈！但是很抱歉，这个我解决不了，至少单靠Adblock应该是没法解决的。

好的，感谢回复。
