### ISSUE TITLE
https://czzy.top/

### ISSUE THREAD

**Issue by Aloazny** [lingeringsound/adblock_auto#29]
### 使用的拦截器

Via

### 你使用的是那个规则?

混合规则精简版

### 问题描述

大佬，这个网址的图片误杀了，https://www.cz01.vip https://czzy.top

**Comment by lingeringsound** [comment]
! 好的，感谢反馈，添加自定义规则即可。
#@#a[href*=".top"] > img[src]

**Comment by Aloazny** [comment]
好的，感谢大佬！
