### ISSUE TITLE
反馈：https://m.po18wen.net/book/78863/上下广告

### ISSUE THREAD

**Issue by 183868hlj** [lingeringsound/adblock_auto#3]
反馈：
https://m.po18wen.net/book/78863/
上下广告

**Comment by lingeringsound** [comment]
!添加自定义规则
```
po18wen.net##img[style="border: 1px inset #00FF00"]
po18wen.net##[style*="pointer-events: none;"]
##script + [style="padding:0;margin:0;border:0"] + article[id]
||kkjhgfds.top^
```

**Comment by 183868hlj** [comment]
> !添加自定义规则
> 
> ```
> po18wen.net##img[style="border: 1px inset #00FF00"]
> po18wen.net##[style*="pointer-events: none;"]
> ##script + [style="padding:0;margin:0;border:0"] + article[id]
> ||kkjhgfds.top^
> ```

谢谢
