### ISSUE TITLE
误拦截了脚本添加的类

### ISSUE THREAD

**Issue by daybreak1929** [lingeringsound/adblock_auto#30]
### 使用的拦截器

Via

### 你使用的是那个规则?

混合规则精简版

### 问题描述

在启用[移动端bilibili优化](https://update.greasyfork.org/scripts/494644/%E3%80%90%E7%A7%BB%E5%8A%A8%E7%AB%AF%E3%80%91bilibili%E4%BC%98%E5%8C%96.user.js)脚本后恰好会拦截掉视频推荐(即图中的相关推荐)，脚本功能挺完善的也没啥广告效果，应该是误杀
![Screenshot_2024-10-30-18-39-57-394_mark via](https://github.com/user-attachments/assets/0a447e14-94c0-4a1a-bb8c-aa95159ae335)

**Comment by lingeringsound** [comment]
好的，感谢反馈，等下处理。

**Comment by lingeringsound** [comment]
现在应该没问题了
