### ISSUE TITLE
bilibili移动端广告拦截

### ISSUE THREAD

**Issue by Aloazny** [lingeringsound/adblock_auto#31]
### 网址

https://www.bilibili.com/

### 补充说明

请求大佬增加在精简版里添加更多的桌面端规则。

### 你使用的是那个规则?

混合规则精简版

### 使用的拦截器

Via

**Comment by lingeringsound** [comment]
好的，感谢反馈，已经添加，等下等待action更新就行。

**Comment by Aloazny** [comment]
好的，感谢大佬！
