### ISSUE TITLE
规则误杀

### ISSUE THREAD

**Issue by xiaowang16888** [lingeringsound/adblock_auto#32]
### 使用的拦截器

Via

### 你使用的是那个规则?

混合规则精简版

### 问题描述

https://pro.m.jd.com/mall/active/ijURizQ4sh2r12cwVExCX2Sn9yw/index.html?ad_od=4&unionActId=31192&uabt=505_5984_1_0&d=C1Qx6yH&s=&cu=true&utm_source=lianmeng__9__kong&utm_medium=tuiguang&utm_campaign=t_1003137601_&utm_term=6dbdf5ac4d674d0e9ff5eb00a5a41575这个页面被误杀
![Uploading Screenshot_2024-11-09-22-53-54-186_mark.via.gp.jpg…]()

**Comment by lingeringsound** [comment]
- ![Screenshot_2024-11-09-23-04-37-740-edit_bin mt plus](https://github.com/user-attachments/assets/7764335b-485d-4e4e-bcbb-fc299eb7f7b0)

感谢反馈，但是这个我很早就放到白名单了，Via自己的问题，你刷新一下就会出现界面了。

**Comment by xiaowang16888** [comment]
好的，感谢大佬

**Comment by lingeringsound** [comment]
> 好的，感谢大佬

不客气

**Comment by xiaowang16888** [comment]
大佬，直接放行这个域名，就能转跳了，我感觉是因为这个放行规则太短，放行不生效。放行这个规则@@||m.jd.com^就可以了，你看有时间更新一下混合规则精简版，谢谢大佬了

**Comment by lingeringsound** [comment]
好的，感谢反馈，已经添加，等待下午的action自动更新就行。

**Comment by xiaowang16888** [comment]
好的👌

**Comment by xiaowang16888** [comment]
好的👌
