### ISSUE TITLE
/image/20*-*-*/*/$other,~image规则误拦截

### ISSUE THREAD

**Issue by acxcdz** [lingeringsound/adblock_auto#33]
### 使用的拦截器

AdGuard

### 你使用的是那个规则?

其他

### 问题描述

/image/20*-*-*/*/$other,~image
酷安部分应用封面加载不出来

**Comment by lingeringsound** [comment]
好的，感谢反馈，给个链接我看看。

**Comment by acxcdz** [comment]
> 好的，感谢反馈，给个链接我看看。

http://image.coolapk.com/apk_image/2024/0521/21/0_8528_6608_897@480x800.png.t.jpg

**Comment by lingeringsound** [comment]
？你不能能具体点，你用的是Adguard拓展(extension)，还是Adguard for Android？

你是在酷安应用，还是在酷安网页误杀了？

这个用拓展的话，根本拦不到，因为加了`$~image`，非图像类型的规则。

如果是Adguard for Android，那我不建议你用这个规则，因为这规则我本来就没考虑过在Adguard上使用。

**Comment by lingeringsound** [comment]
而且这个图片是`http`不是`https`，你看下你的浏览器是不是支持在`https`网页中加载`http`资源。

**Comment by acxcdz** [comment]
> ？你不能能具体点，你用的是Adguard拓展（extension），还是Adguard for Android？
> 
> 你是在酷安应用，还是在酷安网页误杀了？
> 
> 这个用拓展的话，根本拦不到，因为加了，非图像类型的规则。`$~image`
> 
> 如果是Adguard for Android，那我不建议你用这个规则，因为这规则我本来就没考虑过在Adguard for Android上使用。

酷安应用

**Comment by lingeringsound** [comment]
这个混合规则不应该出现在Adguard for Android，我不知道你为什么要加进去。

这个规则主要是针对网页的，不是APP应用，加入Adguard for Android只会拖慢速度，很多规则都是网页规则，不是Android规则，只适合在拓展(Adguard extension)中使用。

**Comment by acxcdz** [comment]
> ？你不能能具体点，你用的是Adguard拓展（extension），还是Adguard for Android？
> 
> 你是在酷安应用，还是在酷安网页误杀了？
> 
> 这个用拓展的话，根本拦不到，因为加了，非图像类型的规则。`$~image`
> 
> 如果是Adguard for Android，那我不建议你用这个规则，因为这规则我本来就没考虑过在Adguard for Android上使用。

我是在酷安应用误杀的，用的是Adguard for Android，我想我明白了

**Comment by lingeringsound** [comment]
好的，能明白就好，这个规则本来就不是给Adguard for Android使用的，建议移除。
