### ISSUE TITLE
拦截了91视频广告元素导致播放视频要等待10秒，无法手动跳过广告播放视频

### ISSUE THREAD

**Issue by damengzhu** [lingeringsound/adblock_auto#36]
### 使用的拦截器

Xbrowser(X浏览器)

### 你使用的是那个规则?

混合规则精简版

### 问题描述

https://91porn.com/view_video.php?viewkey=08da1098713e2f3797db&c=xsnob&viewtype=&category=

**Comment by damengzhu** [comment]
不是10秒，是20秒

**Comment by lingeringsound** [comment]
> 不是10秒，是20秒
- 感谢反馈！
但我觉得还是算了吧，我这边拦不拦截，都得等广告出现，不想找那个规则拦的了，就这样吧。

**Comment by lingeringsound** [comment]
已经根据你的规则提交，加了白名单，感谢！
