### ISSUE TITLE
恩山论坛误杀

### ISSUE THREAD

**Issue by Aloazny** [lingeringsound/adblock_auto#43]
### 使用的拦截器

Via

### 你使用的是那个规则?

混合规则精简版

### 问题描述

[恩山论坛](https://www.right.com.cn/forum/forum.php)的logo图片被杀了，请大佬放行一下。

**Comment by lingeringsound** [comment]
!好的，感谢反馈，添加自定义规则即可
@@||right.com.cn/forum/static/image/common/logo_m.svg$domain=right.com.cn
