### ISSUE TITLE
哔哩哔哩首页内容误杀

### ISSUE THREAD

**Issue by violet-yi** [lingeringsound/adblock_auto#44]
### 使用的拦截器

uBlock(拓展)

### 你使用的是那个规则?

混合规则

### 问题描述

<img width="1072" alt="1" src="https://github.com/user-attachments/assets/6f154f8c-82dc-450e-96b1-8498b58ab31d" />
<img width="1077" alt="3" src="https://github.com/user-attachments/assets/f14abd7a-be04-47a9-8f3a-0ca9f06b2305" />
测试停用规则后恢复显示。

**Comment by lingeringsound** [comment]
! 好的，感谢反馈，添加自定义规则放行即可
bilibili.com#@?#.is-rcmd:has(>div:not(div:has(div)))

**Comment by lingeringsound** [comment]
如果订阅了[cjx82630](https://github.com/cjx82630/cjxlist/blob/refs%2Fheads%2Fmaster/cjx-annoyance.txt#L497-L497)大佬的[这条规则](https://github.com/cjx82630/cjxlist/blob/refs%2Fheads%2Fmaster/cjx-annoyance.txt#L497-L497)，记得先放在白名单，我后面反馈一下。
