### ISSUE TITLE
第一版主广告拦截

### ISSUE THREAD

**Issue by Aloazny** [lingeringsound/adblock_auto#6]
https://xooxooxoo.xyz/?u=http://www.diyibanzhu333.xyz/&p=/

**Comment by lingeringsound** [comment]
!添加自定义规则
||uoosqk.xyz^
||vuyibsm.icu^

**Comment by Aloazny** [comment]
> !添加自定义规则
> ||uoosqk.xyz^
> ||vuyibsm.icu^

好的，谢谢大佬！
