### ISSUE TITLE
缩减体积

### ISSUE THREAD

**Issue by Aloazny** [lingeringsound/adblock_auto#8]
### 使用的拦截器

Via, Xbrowser(X浏览器), 嗅觉浏览器, B仔浏览器, Rians浏览器, AdGuard, uBlock

### 你使用的是那个规则?

混合规则精简版

### 预期描述

请求缩减[混合规则精简版](https://lingeringsound.github.io/adblock_auto/Rules/adblock_auto_lite.txt)的体积，之前还是`500kb`现在已经到`1.4mb`了，有点太大了。

**Comment by lingeringsound** [comment]
OK，后续有空会尝试精简一下的😂。

**Comment by lingeringsound** [comment]
已经完成大部分缩减，[混合规则精简版](
https://lingeringsound.github.io/adblock_auto/Rules/adblock_auto_lite.txt)
