### ISSUE TITLE
##img[alt*="广告"][src]

### ISSUE THREAD

**Issue by Aloazny** [lingeringsound/adblock_auto#9]
### 规则类型

放行

### 规则

#@#img[alt*="广告"][src]

### 提交此规则的原因

大佬，这条杀伤力规则太大，好像会导致cpu占用异常😔。

**Comment by lingeringsound** [comment]
你是用什么规则，在那个网站上出现问题？是用浏览器还是拓展？我这边好像挺正常的😂。

**Comment by Aloazny** [comment]
Radmi pad (Android12) `webview109` 就是在[哔哩哔哩](https://bilibili.com) 上面看视频，用的可拓浏览器，Adguard拓展。

**Comment by lingeringsound** [comment]
我对bilibili已经放行了啊😱，离谱
```
pornpics.com,pornpics.de,nr19.cn,bilibili.com,youku.com,v.qq.com,acfun.cn#@#img[alt*="广告"][src]
```

**Comment by Aloazny** [comment]
好吧，我再试试，感谢大佬！

**Comment by Aloazny** [comment]
好像是联发科的锅，不知道怎么回事，用scene查看cpu占用又正常了，抱歉，打扰了。
